POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "My first article",
  "description": "This is my first article",
  "url": "http://example.com/articles/1",
  "image": "http://example.com/articles/1/image.jpg"
}

###
GET http://localhost:3000/api/articles
