POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "My Second Article",
  "description": "This is my second article",
  "url": "http://example.com/articles/2",
  "image": "http://example.com/articles/2/image.jpg",
  "keywords": ["Second", "article"]
}

###
GET http://localhost:3000/api/articles
